-----現在日付----------
SELECT CURRENT_DATE;

-----現在日時----------
SELECT CURRENT_TIME;

-----現在日時----------
SELECT CURRENT_TIMESTAMP;

-----現在日時----------
SELECT CURRENT_TIMESTAMP,
      EXTRACT(YEAR FROM CURRENT_TIMESTAMP) AS year,
      EXTRACT(MONTH FROM CURRENT_TIMESTAMP) AS month,
      EXTRACT(DAY FROM CURRENT_TIMESTAMP) AS day,
      EXTRACT(HOUR FROM CURRENT_TIMESTAMP) AS hour,
      EXTRACT(MINUTE FROM CURRENT_TIMESTAMP) AS minute,
      EXTRACT(SECOND FROM CURRENT_TIMESTAMP) AS second
      ;